// Demo catalogue for VendorZone. Photos live in seed/images (Unsplash, free licence,
// credits in seed/images/CREDITS.json). Everything here is sample data.

const PASSWORD = "Demo@1234";
const DOMAIN = "demo.vendorzone.tech";

const shops = [
  {
    slug: "northline-audio",
    name: "Northline Audio",
    description:
      "Headphones and speakers tuned by people who actually listen. Every product is tested in our Portland studio before it ships.",
    address: "412 NW Glisan St, Portland, OR",
    zipCode: 97209,
    phoneNumber: 5035550142,
  },
  {
    slug: "technest",
    name: "TechNest",
    description:
      "Everyday tech without the markup. Laptops, phones, cameras and desk gear, each with a 2-year warranty.",
    address: "1800 S Congress Ave, Austin, TX",
    zipCode: 78704,
    phoneNumber: 5125550177,
  },
  {
    slug: "atelier-moss",
    name: "Atelier Moss",
    description:
      "Small-batch wardrobe staples in natural fabrics. Cut to last, priced to wear every day.",
    address: "88 Bedford Ave, Brooklyn, NY",
    zipCode: 11211,
    phoneNumber: 7185550123,
  },
  {
    slug: "stride-lab",
    name: "Stride Lab",
    description:
      "Footwear and outdoor gear for people who move. Tested on city streets and mountain trails.",
    address: "2020 Pearl St, Boulder, CO",
    zipCode: 80302,
    phoneNumber: 3035550168,
  },
  {
    slug: "hearth-and-co",
    name: "Hearth & Co.",
    description:
      "Slow-living pieces for the home and kitchen: stoneware, linen, cast iron and good coffee gear.",
    address: "30 Biltmore Ave, Asheville, NC",
    zipCode: 28801,
    phoneNumber: 8285550191,
  },
  {
    slug: "verdant-beauty",
    name: "Verdant Beauty",
    description:
      "Plant-forward skincare and fragrance. Dermatologist-reviewed formulas, never tested on animals.",
    address: "715 N La Brea Ave, Los Angeles, CA",
    zipCode: 90038,
    phoneNumber: 3235550136,
  },
  {
    slug: "paper-and-pine",
    name: "Paper & Pine",
    description:
      "Stationery, desk goods and gifts worth keeping. Wrapped by hand and shipped plastic-free.",
    address: "505 Nicollet Mall, Minneapolis, MN",
    zipCode: 55402,
    phoneNumber: 6125550114,
  },
];

const CATEGORIES = {
  electronics: "Electronics",
  fashion: "Fashion",
  shoes: "Shoes",
  home: "Home & Living",
  beauty: "Beauty & Care",
  sports: "Sports & Outdoors",
  kitchen: "Kitchen & Coffee",
  gifts: "Gifts & Stationery",
};

// slug doubles as the image file prefix: <slug>-1.jpg (main), <slug>-2.jpg (alt)
const products = [
  // ---- Electronics
  {
    slug: "aurora-anc-headphones",
    shop: "northline-audio",
    category: "electronics",
    name: "Aurora ANC Wireless Headphones",
    price: 189,
    was: 249,
    stock: 42,
    sold: 318,
    tags: "headphones, wireless, noise cancelling, audio",
    description:
      "Over-ear headphones with hybrid active noise cancelling and 40mm drivers tuned for a warm, even sound.\nBattery lasts 38 hours with ANC on, and a 10-minute quick charge gives you another 6. Bluetooth 5.3 multipoint keeps a phone and laptop connected at once.\nIn the box: carry case, USB-C cable and a 3.5mm cable for flights.",
  },
  {
    slug: "orbit-bluetooth-speaker",
    shop: "northline-audio",
    category: "electronics",
    name: "Orbit Portable Bluetooth Speaker",
    price: 79,
    was: 99,
    stock: 65,
    sold: 540,
    tags: "speaker, bluetooth, portable, waterproof",
    description:
      "A palm-sized speaker with surprisingly full, room-filling sound and a passive bass radiator.\nIP67 rated, so it handles rain, pools and sandy beaches, and it floats. Up to 20 hours of playback; pair two for stereo.",
  },
  {
    slug: "pulse-smartwatch",
    shop: "technest",
    category: "electronics",
    name: "Pulse Series 5 Smartwatch",
    price: 229,
    was: 279,
    stock: 30,
    sold: 205,
    tags: "smartwatch, fitness, wearable, gps",
    description:
      "A bright always-on AMOLED display, built-in GPS and heart-rate, sleep and blood-oxygen tracking in a 9mm aluminium case.\nTracks 100+ workouts, shows notifications from your phone and lasts up to 5 days per charge. Water resistant to 50 metres.",
  },
  {
    slug: "mono-mechanical-keyboard",
    shop: "technest",
    category: "electronics",
    name: "Mono 75% Mechanical Keyboard",
    price: 119,
    was: 149,
    stock: 54,
    sold: 160,
    tags: "keyboard, mechanical, desk, wireless",
    description:
      "A compact 75% layout with a gasket-mounted plate for a soft, thocky typing feel.\nHot-swappable switches (linear, factory-lubed), PBT keycaps, and wireless via Bluetooth or 2.4GHz with a 4,000mAh battery. Works with Mac and Windows.",
  },
  {
    slug: "frame-mirrorless-camera",
    shop: "technest",
    category: "electronics",
    name: "Frame X2 Mirrorless Camera",
    price: 899,
    was: 1099,
    stock: 12,
    sold: 48,
    tags: "camera, mirrorless, photography, 4k",
    description:
      "26MP APS-C sensor, 5-axis in-body stabilisation and 4K/60 video with no crop.\nFast hybrid autofocus tracks eyes and animals, and the weather-sealed magnesium body feels great in the hand. Kit includes a 16-50mm lens and battery grip adapter.",
  },
  {
    slug: "slate-ultrabook",
    shop: "technest",
    category: "electronics",
    name: "Slate 14 Ultrabook",
    price: 1149,
    was: 1349,
    stock: 18,
    sold: 73,
    tags: "laptop, ultrabook, work, portable",
    description:
      "A 1.2kg aluminium ultrabook with a 14-inch 2.8K display, 16GB RAM and a 512GB SSD.\nQuiet fanless cooling, a backlit keyboard with real travel and up to 16 hours of battery. Thunderbolt 4, Wi-Fi 6E and a 1080p webcam with privacy shutter.",
  },
  {
    slug: "nova-smartphone",
    shop: "technest",
    category: "electronics",
    name: "Nova 12 5G Smartphone",
    price: 549,
    was: 649,
    stock: 36,
    sold: 190,
    tags: "phone, smartphone, 5g, android",
    description:
      "A 6.5-inch 120Hz OLED display, 50MP main camera with optical stabilisation and a 5,000mAh battery that easily gets through two days.\n256GB storage, 8GB RAM, 67W fast charging and 5 years of security updates. Unlocked, dual-SIM.",
  },

  // ---- Fashion
  {
    slug: "cotton-hoodie",
    shop: "atelier-moss",
    category: "fashion",
    name: "Heavyweight Cotton Hoodie",
    price: 64,
    was: 89,
    stock: 80,
    sold: 412,
    tags: "hoodie, cotton, streetwear, unisex",
    description:
      "A 450gsm brushed-back cotton hoodie that holds its shape wash after wash. Double-layered hood, ribbed cuffs and a roomy, slightly boxy cut.\nPre-shrunk and garment-dyed for a soft, lived-in feel. Unisex sizing, XS–XXL.",
  },
  {
    slug: "raw-denim-jacket",
    shop: "atelier-moss",
    category: "fashion",
    name: "Raw Denim Trucker Jacket",
    price: 118,
    was: 148,
    stock: 34,
    sold: 126,
    tags: "denim, jacket, outerwear, classic",
    description:
      "12oz Japanese selvedge denim cut in a classic trucker fit with copper rivets and a button front.\nStiff at first, then it fades to you. Cold wash and hang dry for the best character.",
  },
  {
    slug: "canvas-tote",
    shop: "atelier-moss",
    category: "fashion",
    name: "Everyday Canvas Tote",
    price: 29,
    was: 39,
    stock: 150,
    sold: 689,
    tags: "tote, bag, canvas, everyday",
    description:
      "Heavy 12oz organic cotton canvas with reinforced stitching on the handles and an inside zip pocket.\nFits a 15-inch laptop, a lunch and a jacket. Machine washable.",
  },
  {
    slug: "aviator-sunglasses",
    shop: "atelier-moss",
    category: "fashion",
    name: "Classic Aviator Sunglasses",
    price: 58,
    was: 79,
    stock: 70,
    sold: 233,
    tags: "sunglasses, aviator, accessories, uv400",
    description:
      "Lightweight metal frames with polarised, UV400 lenses and adjustable silicone nose pads.\nComes with a hard case and microfibre cloth.",
  },
  {
    slug: "merino-sweater",
    shop: "atelier-moss",
    category: "fashion",
    name: "Merino Crew Sweater",
    price: 96,
    was: 129,
    stock: 45,
    sold: 154,
    tags: "sweater, merino, knitwear, winter",
    description:
      "Fine-gauge 100% extra-fine merino wool that's warm without the bulk and naturally resists odour.\nA clean crew neck with ribbed trims. Wears well alone or layered; machine washable on the wool cycle.",
  },
  {
    slug: "chronograph-watch",
    shop: "atelier-moss",
    category: "fashion",
    name: "Heritage Chronograph Watch",
    price: 169,
    was: 219,
    stock: 22,
    sold: 87,
    tags: "watch, chronograph, leather, accessories",
    description:
      "A 40mm stainless steel case with a sapphire-coated crystal, Japanese quartz chronograph movement and a tan vegetable-tanned leather strap.\nWater resistant to 50 metres. Two-year warranty.",
  },

  // ---- Shoes
  {
    slug: "aero-runner",
    shop: "stride-lab",
    category: "shoes",
    name: "Aero Runner Sneakers",
    price: 109,
    was: 139,
    stock: 60,
    sold: 377,
    tags: "running, sneakers, shoes, lightweight",
    description:
      "A breathable engineered-mesh upper over a responsive foam midsole, built for daily miles.\nOnly 245g (size 9) with a rocker geometry that makes toe-off feel easy. Reflective details for early runs.",
  },
  {
    slug: "court-sneakers",
    shop: "stride-lab",
    category: "shoes",
    name: "Court Classic White Sneakers",
    price: 89,
    was: 110,
    stock: 90,
    sold: 521,
    tags: "sneakers, leather, white, casual",
    description:
      "Full-grain leather uppers, a gum rubber outsole and a cushioned insole. Goes with everything and cleans up with a damp cloth.\nTrue to size; the leather softens after a few wears.",
  },
  {
    slug: "trail-hiker-boots",
    shop: "stride-lab",
    category: "shoes",
    name: "Trail Hiker Waterproof Boots",
    price: 139,
    was: 179,
    stock: 28,
    sold: 142,
    tags: "hiking, boots, waterproof, trail",
    description:
      "Waterproof membrane, a grippy 5mm lug outsole and a padded ankle collar that keeps debris out.\nSupportive enough for a loaded pack, light enough for all-day trails. Breaks in quickly.",
  },
  {
    slug: "suede-chelsea-boots",
    shop: "stride-lab",
    category: "shoes",
    name: "Suede Chelsea Boots",
    price: 149,
    was: 189,
    stock: 31,
    sold: 109,
    tags: "boots, chelsea, suede, formal",
    description:
      "Soft Italian suede with elastic gussets, a pull tab and a stacked leather heel.\nLeather-lined for comfort. Treat with a suede protector before the first wear.",
  },
  {
    slug: "canvas-slip-ons",
    shop: "stride-lab",
    category: "shoes",
    name: "Canvas Slip-Ons",
    price: 49,
    was: 65,
    stock: 110,
    sold: 298,
    tags: "slip-on, canvas, casual, summer",
    description:
      "Easy canvas slip-ons with a cushioned footbed and flexible rubber sole. Light enough for travel, casual enough for the weekend.",
  },
  {
    slug: "retro-high-tops",
    shop: "stride-lab",
    category: "shoes",
    name: "Retro High-Top Sneakers",
    price: 79,
    was: 99,
    stock: 64,
    sold: 245,
    tags: "sneakers, high-top, retro, canvas",
    description:
      "A throwback high-top with a vulcanised sole, metal eyelets and a padded collar. Durable canvas that looks better the more you wear it.",
  },

  // ---- Home & Living
  {
    slug: "arc-floor-lamp",
    shop: "hearth-and-co",
    category: "home",
    name: "Arc Linen Floor Lamp",
    price: 139,
    was: 179,
    stock: 20,
    sold: 64,
    tags: "lamp, lighting, floor lamp, linen",
    description:
      "A slim brass-finish stem with a pleated linen shade that gives off a warm, diffused glow.\nStands 158cm tall with an inline dimmer. Takes any E27 bulb (bulb not included).",
  },
  {
    slug: "stoneware-vase-trio",
    shop: "hearth-and-co",
    category: "home",
    name: "Stoneware Vase Trio",
    price: 54,
    was: 72,
    stock: 46,
    sold: 131,
    tags: "vase, ceramic, decor, stoneware",
    description:
      "Three hand-thrown stoneware vases in graduated sizes with a soft matte glaze. No two are exactly alike.\nWatertight, and equally good with dried stems or on their own.",
  },
  {
    slug: "linen-throw",
    shop: "hearth-and-co",
    category: "home",
    name: "Stonewashed Linen Throw",
    price: 69,
    was: 89,
    stock: 58,
    sold: 178,
    tags: "throw, linen, blanket, bedroom",
    description:
      "Stonewashed European flax linen that is soft from the first use and gets better with every wash.\n130 × 180cm with hand-knotted fringe. Layer it over the sofa or the foot of the bed.",
  },
  {
    slug: "soy-candle",
    shop: "hearth-and-co",
    category: "home",
    name: "Soy Wax Candle, Cedar & Fig",
    price: 24,
    was: 32,
    stock: 200,
    sold: 764,
    tags: "candle, soy, scented, gift",
    description:
      "Hand-poured soy wax with a cotton wick and notes of cedarwood, green fig and a little black pepper.\n220g, around 45 hours of burn time. Comes in a reusable tin.",
  },
  {
    slug: "lounge-chair",
    shop: "hearth-and-co",
    category: "home",
    name: "Oak Frame Lounge Chair",
    price: 329,
    was: 429,
    stock: 9,
    sold: 37,
    tags: "chair, furniture, oak, lounge",
    description:
      "Solid oak frame with mortise-and-tenon joints and a deep, supportive seat in washable cotton-linen.\nAssembles in minutes with the included tool. 5-year frame warranty.",
  },
  {
    slug: "aloe-ceramic-pot",
    shop: "hearth-and-co",
    category: "home",
    name: "Aloe Vera in Ceramic Pot",
    price: 22,
    was: 29,
    stock: 75,
    sold: 302,
    tags: "plant, aloe, ceramic, decor",
    description:
      "A healthy, easy-care aloe vera in a 12cm white ceramic pot with a drainage tray.\nLikes bright light and a drink every two weeks. Ships carefully packed.",
  },

  // ---- Beauty & Care
  {
    slug: "vitamin-c-serum",
    shop: "verdant-beauty",
    category: "beauty",
    name: "Vitamin C Brightening Serum",
    price: 34,
    was: 44,
    stock: 120,
    sold: 903,
    tags: "serum, vitamin c, skincare, brightening",
    description:
      "15% stabilised vitamin C with ferulic acid and hyaluronic acid to even tone and add glow.\nLightweight, fragrance-free and non-sticky; use mornings under sunscreen. 30ml in a UV-protective glass bottle.",
  },
  {
    slug: "rose-parfum",
    shop: "verdant-beauty",
    category: "beauty",
    name: "Rose & Amber Eau de Parfum",
    price: 72,
    was: 95,
    stock: 40,
    sold: 211,
    tags: "perfume, fragrance, rose, amber",
    description:
      "Damask rose and pink pepper open into a warm amber and sandalwood base. Soft, lasting and not too sweet.\n50ml, refillable glass bottle.",
  },
  {
    slug: "matte-lipstick",
    shop: "verdant-beauty",
    category: "beauty",
    name: "Velvet Matte Lipstick",
    price: 22,
    was: 28,
    stock: 160,
    sold: 655,
    tags: "lipstick, makeup, matte, vegan",
    description:
      "A comfortable, buildable matte with high-pigment colour and a creamy glide. Vegan and cruelty-free.\nRefillable aluminium case, 3.5g.",
  },
  {
    slug: "hydra-day-cream",
    shop: "verdant-beauty",
    category: "beauty",
    name: "Hydra Day Cream SPF 30",
    price: 38,
    was: 48,
    stock: 95,
    sold: 380,
    tags: "moisturiser, spf, skincare, hydration",
    description:
      "A silky daily moisturiser with ceramides, niacinamide and a mineral SPF 30 that leaves no white cast.\nSuitable for sensitive skin. 50ml jar.",
  },
  {
    slug: "beech-hair-brush",
    shop: "verdant-beauty",
    category: "beauty",
    name: "Beechwood Detangling Brush",
    price: 18,
    was: 24,
    stock: 140,
    sold: 322,
    tags: "hair, brush, beechwood, detangling",
    description:
      "A sustainably sourced beechwood brush with boar-and-nylon bristles that glide through knots and spread natural oils.\nSmooth, anti-static and gentle on the scalp.",
  },
  {
    slug: "bath-ritual-set",
    shop: "verdant-beauty",
    category: "beauty",
    name: "Bath Ritual Gift Set",
    price: 46,
    was: 62,
    stock: 52,
    sold: 187,
    tags: "bath, spa, gift set, self care",
    description:
      "Body oil, bath salts and a bamboo dry brush in a reusable linen pouch.\nLavender and eucalyptus scents. A thoughtful gift, or a treat for yourself.",
  },

  // ---- Sports & Outdoors
  {
    slug: "cork-yoga-set",
    shop: "stride-lab",
    category: "sports",
    name: "Cork Yoga Mat & Block Set",
    price: 59,
    was: 79,
    stock: 55,
    sold: 266,
    tags: "yoga, mat, cork, fitness",
    description:
      "A 5mm natural cork and tree-rubber mat that grips better when you sweat, plus a matching cork block.\n183 × 61cm, antimicrobial and easy to wipe clean. Includes a carry strap.",
  },
  {
    slug: "hex-dumbbells",
    shop: "stride-lab",
    category: "sports",
    name: "Hex Rubber Dumbbells (pair)",
    price: 89,
    was: 119,
    stock: 38,
    sold: 158,
    tags: "dumbbells, weights, gym, strength",
    description:
      "Rubber-coated hex dumbbells that won't roll away and protect your floors. Knurled steel handles for a secure grip.\nSold as a pair, 10kg each.",
  },
  {
    slug: "steel-bottle",
    shop: "stride-lab",
    category: "sports",
    name: "Insulated Steel Bottle 750ml",
    price: 27,
    was: 35,
    stock: 210,
    sold: 812,
    tags: "bottle, insulated, steel, hydration",
    description:
      "Double-wall vacuum insulated: cold for 24 hours, hot for 12. BPA-free, leak-proof lid and a powder-coat finish that doesn't sweat.\nFits most cup holders.",
  },
  {
    slug: "trail-backpack",
    shop: "stride-lab",
    category: "sports",
    name: "Trail 28L Daypack",
    price: 99,
    was: 129,
    stock: 33,
    sold: 119,
    tags: "backpack, hiking, daypack, outdoor",
    description:
      "A 28-litre daypack with a ventilated back panel, hip belt, hydration sleeve and a built-in rain cover.\nRip-stop recycled nylon at just 780g.",
  },
  {
    slug: "dome-tent",
    shop: "stride-lab",
    category: "sports",
    name: "Dome Camping Tent, 2-Person",
    price: 159,
    was: 209,
    stock: 17,
    sold: 71,
    tags: "tent, camping, outdoor, 3-season",
    description:
      "A freestanding 3-season dome that pitches in under five minutes with colour-coded poles.\nTaped seams, a full-coverage rainfly and two vestibules for gear. Packs down to 48 × 16cm, 2.1kg.",
  },
  {
    slug: "resistance-band-kit",
    shop: "stride-lab",
    category: "sports",
    name: "Resistance Band Kit (5 levels)",
    price: 24,
    was: 34,
    stock: 180,
    sold: 590,
    tags: "resistance bands, workout, fitness, home gym",
    description:
      "Five loop bands from light to extra-heavy in natural latex, with a mesh carry bag and an exercise guide.\nGreat for warm-ups, rehab, glutes and travel workouts.",
  },

  // ---- Kitchen & Coffee
  {
    slug: "pour-over-set",
    shop: "hearth-and-co",
    category: "kitchen",
    name: "Pour-Over Coffee Set",
    price: 62,
    was: 82,
    stock: 49,
    sold: 224,
    tags: "coffee, pour-over, carafe, brewing",
    description:
      "A borosilicate glass carafe with a wooden collar, a reusable steel filter and a measuring scoop.\nBrews 600ml, roughly two big mugs of clean, bright coffee. Dishwasher safe (except the collar).",
  },
  {
    slug: "stoneware-cups",
    shop: "hearth-and-co",
    category: "kitchen",
    name: "Hand-Glazed Stoneware Cups (4)",
    price: 44,
    was: 58,
    stock: 66,
    sold: 297,
    tags: "mugs, cups, stoneware, kitchen",
    description:
      "Four 250ml cups in a speckled two-tone reactive glaze. Each is slightly different, in the best way.\nDishwasher and microwave safe.",
  },
  {
    slug: "walnut-board",
    shop: "hearth-and-co",
    category: "kitchen",
    name: "Walnut Serving & Cutting Board",
    price: 52,
    was: 68,
    stock: 41,
    sold: 143,
    tags: "cutting board, walnut, serving, kitchen",
    description:
      "A solid walnut board with a leather hanging strap. Gentle on knife edges, and handsome enough to serve from.\nFinished in food-safe mineral oil. 45 × 25cm.",
  },
  {
    slug: "cast-iron-skillet",
    shop: "hearth-and-co",
    category: "kitchen",
    name: "Pre-Seasoned Cast Iron Skillet, 10in",
    price: 39,
    was: 49,
    stock: 77,
    sold: 438,
    tags: "skillet, cast iron, cookware, kitchen",
    description:
      "A 10-inch cast iron skillet pre-seasoned with flaxseed oil. Works on gas, induction, in the oven and over a campfire.\nBuilds a naturally non-stick surface with use and lasts for generations.",
  },
  {
    slug: "espresso-machine",
    shop: "hearth-and-co",
    category: "kitchen",
    name: "Barista Pro Espresso Machine",
    price: 429,
    was: 549,
    stock: 14,
    sold: 52,
    tags: "espresso, coffee machine, barista, kitchen",
    description:
      "A 15-bar Italian pump, a PID-controlled boiler and a commercial-style steam wand for proper microfoam.\nHeats up in 30 seconds. Includes a pressurised and a non-pressurised basket. 1.8L removable tank.",
  },
  {
    slug: "forged-knife-set",
    shop: "hearth-and-co",
    category: "kitchen",
    name: "Forged Kitchen Knife Set (4 pc)",
    price: 134,
    was: 179,
    stock: 26,
    sold: 98,
    tags: "knives, chef knife, kitchen, forged",
    description:
      "Chef's, bread, utility and paring knives forged from German high-carbon steel with full-tang pakkawood handles.\nHand-sharpened to 15° and balanced for control.",
  },

  // ---- Gifts & Stationery
  {
    slug: "dot-grid-notebook",
    shop: "paper-and-pine",
    category: "gifts",
    name: "A5 Dot-Grid Notebook",
    price: 16,
    was: 22,
    stock: 300,
    sold: 1180,
    tags: "notebook, stationery, journal, dot grid",
    description:
      "Lay-flat A5 notebook with 192 pages of 120gsm fountain-pen-friendly paper, a ribbon marker and a back pocket.\nSewn binding that stays open on the desk.",
  },
  {
    slug: "brass-fountain-pen",
    shop: "paper-and-pine",
    category: "gifts",
    name: "Brass Fountain Pen",
    price: 42,
    was: 55,
    stock: 64,
    sold: 207,
    tags: "pen, fountain pen, brass, writing",
    description:
      "A solid brass pen with a steel nib (medium), a screw cap and a smooth, balanced weight. The brass develops a patina over time.\nTakes standard international cartridges; includes a converter and two cartridges.",
  },
  {
    slug: "felt-desk-mat",
    shop: "paper-and-pine",
    category: "gifts",
    name: "Wool Felt Desk Mat",
    price: 39,
    was: 52,
    stock: 88,
    sold: 316,
    tags: "desk mat, felt, workspace, wool",
    description:
      "A 3mm wool-blend felt mat, 80 × 40cm with rounded corners and a non-slip backing.\nSofter on wrists, quieter on keys and great under a laptop and mouse.",
  },
  {
    slug: "self-care-gift-box",
    shop: "paper-and-pine",
    category: "gifts",
    name: "Self-Care Gift Box",
    price: 58,
    was: 75,
    stock: 44,
    sold: 173,
    tags: "gift box, gift, self care, present",
    description:
      "A hand-packed box with a soy candle, herbal tea, a linen eye mask, bath salts and a handwritten note card.\nPlastic-free packaging, ready to give.",
  },
  {
    slug: "watercolor-set",
    shop: "paper-and-pine",
    category: "gifts",
    name: "Artist Watercolor Set, 24 pans",
    price: 34,
    was: 45,
    stock: 72,
    sold: 195,
    tags: "watercolor, art, paint, hobby",
    description:
      "24 richly pigmented half-pans in a compact tin with a mixing palette, plus two travel brushes.\nSmooth to blend and lightfast. A great start for beginners.",
  },
  {
    slug: "instant-camera",
    shop: "paper-and-pine",
    category: "gifts",
    name: "Instant Film Camera",
    price: 99,
    was: 129,
    stock: 29,
    sold: 140,
    tags: "camera, instant, film, retro",
    description:
      "A point-and-shoot instant camera with automatic exposure, a built-in flash and a selfie mirror.\nUses standard instant film packs (sold separately). Prints in about 90 seconds.",
  },
];

// Flash sales. `product` borrows that product's photos; `daysLeft`/`startsIn` are relative to the seed time.
const events = [
  {
    shop: "northline-audio",
    product: "aurora-anc-headphones",
    name: "Weekend Audio Sale: Aurora ANC",
    price: 149,
    stock: 25,
    sold: 61,
    startedAgo: 2,
    daysLeft: 3,
    description:
      "Our best-selling noise-cancelling headphones at their lowest price of the season. Limited stock, while the sale lasts.",
  },
  {
    shop: "technest",
    product: "pulse-smartwatch",
    name: "Smartwatch Launch Week",
    price: 179,
    stock: 20,
    sold: 33,
    startedAgo: 1,
    daysLeft: 6,
    description:
      "The Pulse Series 5 for $100 off. GPS, sleep tracking and a five-day battery, with a free spare strap while stocks last.",
  },
  {
    shop: "verdant-beauty",
    product: "vitamin-c-serum",
    name: "Glow Up Friday: Vitamin C Serum",
    price: 22,
    stock: 80,
    sold: 126,
    startedAgo: 3,
    daysLeft: 4,
    description:
      "Half price on our most-loved serum. One bottle per customer and gone when the stock is.",
  },
  {
    shop: "atelier-moss",
    product: "raw-denim-jacket",
    name: "Autumn Layers Edit: Denim Jacket",
    price: 89,
    stock: 18,
    sold: 22,
    startedAgo: 2,
    daysLeft: 9,
    description:
      "The Raw Denim Trucker at its best price. It goes with everything and gets better with every wear.",
  },
  {
    shop: "stride-lab",
    product: "trail-hiker-boots",
    name: "Trail Season Kickoff: Hiker Boots",
    price: 99,
    stock: 15,
    sold: 17,
    startedAgo: 1,
    daysLeft: 11,
    description:
      "Waterproof, supportive and broken-in fast. Save $80 on the boots our guides actually wear.",
  },
  {
    shop: "hearth-and-co",
    product: "pour-over-set",
    name: "Slow Mornings: Pour-Over Set",
    price: 44,
    stock: 40,
    sold: 29,
    startedAgo: 4,
    daysLeft: 14,
    description:
      "Everything for a better morning cup: carafe, steel filter and scoop. A little ritual for less.",
  },
  {
    shop: "paper-and-pine",
    product: "felt-desk-mat",
    name: "Desk Refresh Drop (starts soon)",
    price: 29,
    stock: 60,
    sold: 0,
    startedAgo: -3, // starts in 3 days
    daysLeft: 10,
    description:
      "Our wool felt desk mat at launch pricing. Set a reminder: the first 60 go quickly.",
  },
];

// shop → coupon codes (percent off that shop's items; min spend / max discount in $)
const coupons = [
  { shop: "northline-audio", name: "AUDIO15", value: 15, minAmount: 100, maxAmount: 40 },
  { shop: "technest", name: "TECH10", value: 10, minAmount: 200, maxAmount: 120 },
  { shop: "atelier-moss", name: "MOSS20", value: 20, minAmount: 60, maxAmount: 35 },
  { shop: "stride-lab", name: "STRIDE15", value: 15, minAmount: 80, maxAmount: 30 },
  { shop: "hearth-and-co", name: "WELCOME10", value: 10, minAmount: 40, maxAmount: 25 },
  { shop: "verdant-beauty", name: "GLOW20", value: 20, minAmount: 30, maxAmount: 20 },
  { shop: "paper-and-pine", name: "PAPER10", value: 10, minAmount: 25, maxAmount: 15 },
];

// buyers: the first one is the demo account
const buyers = [
  { name: "Alex Morgan", slug: "buyer", phone: 4155550101 },
  { name: "Sofia Reyes", slug: "sofia.reyes", phone: 6465550122 },
  { name: "Jamal Carter", slug: "jamal.carter", phone: 3125550175 },
  { name: "Priya Nair", slug: "priya.nair", phone: 2065550168 },
  { name: "Daniel Okafor", slug: "daniel.okafor", phone: 7135550149 },
  { name: "Mei Huang", slug: "mei.huang", phone: 4085550133 },
  { name: "Emma Whitfield", slug: "emma.whitfield", phone: 6175550190 },
  { name: "Tomás Bianchi", slug: "tomas.bianchi", phone: 3055550117 },
  { name: "Chloe Ortiz", slug: "chloe.ortiz", phone: 5125550162 },
  { name: "Ivan Petrov", slug: "ivan.petrov", phone: 2125550158 },
  { name: "Rachel Adler", slug: "rachel.adler", phone: 3105550184 },
  { name: "Noah Sullivan", slug: "noah.sullivan", phone: 7205550126 },
  { name: "Lena Fischer", slug: "lena.fischer", phone: 9175550171 },
  { name: "Bruno Garcia", slug: "bruno.garcia", phone: 8015550139 },
];

const addresses = [
  { address1: "221 Hayes St", address2: "Apt 4B", city: "San Francisco", country: "United States", zipCode: "94102" },
  { address1: "47 W 13th St", address2: "", city: "New York", country: "United States", zipCode: "10011" },
  { address1: "1400 N Dearborn Pkwy", address2: "Unit 12", city: "Chicago", country: "United States", zipCode: "60610" },
  { address1: "909 Pike St", address2: "", city: "Seattle", country: "United States", zipCode: "98101" },
  { address1: "2300 Main St", address2: "Suite 6", city: "Houston", country: "United States", zipCode: "77002" },
  { address1: "55 Rue du Faubourg", address2: "", city: "Montreal", country: "Canada", zipCode: "H2X1Y4" },
];

// Review text, by category: short, specific-sounding, a few mixed
const reviewText = {
  electronics: [
    [5, "Setup took two minutes and it has been rock solid since. Exactly what I wanted."],
    [5, "Build quality is far better than I expected at this price. Easy recommendation."],
    [4, "Really good overall. Took a day to get used to it, now I wouldn't switch back."],
    [5, "Arrived fast and well packed. Works perfectly and the battery lasts and lasts."],
    [4, "Great value. Only wish the included cable was a bit longer."],
    [3, "Does the job, though the finish picks up fingerprints more than I'd like."],
    [5, "Bought one for myself and then one as a gift. Everyone loves it."],
    [4, "Solid, well designed and the shop answered my question within the hour."],
  ],
  fashion: [
    [5, "The fabric is lovely and the fit is spot on. I've worn it every week since it arrived."],
    [5, "Looks even better in person. Stitching and finish feel premium."],
    [4, "Great quality for the price. I'd size up if you like a relaxed fit."],
    [5, "Washed it twice and it still looks brand new. Very happy."],
    [4, "Exactly as pictured. Shipping was quick and the packaging was nice."],
    [3, "Nice piece but runs a little small for me. Exchanging for the next size."],
    [5, "Got so many compliments the first time I wore it."],
  ],
  shoes: [
    [5, "Comfortable straight out of the box, no break-in at all."],
    [5, "Great grip and they look sharp. Wore them all day on a city trip, zero blisters."],
    [4, "Really good build. Sizing is true to size for me."],
    [4, "Lighter than they look and very supportive. Would buy again."],
    [3, "Good shoe, but the laces could be better quality. Easy fix."],
    [5, "Third pair from this shop. Consistent quality every time."],
    [5, "Fast delivery and exactly what I hoped for."],
  ],
  home: [
    [5, "Looks beautiful in our living room and feels well made. Worth every cent."],
    [5, "Arrived securely packed. The finish is even nicer in person."],
    [4, "Lovely piece. A touch smaller than I pictured but it works great."],
    [5, "Quality is excellent and it came with clear instructions."],
    [4, "Subtle, well made and easy to live with. Happy with it."],
    [3, "Good product but the colour is slightly lighter than the photos."],
    [5, "Bought it as a housewarming gift and they loved it."],
  ],
  beauty: [
    [5, "My skin has never looked better. Gentle, and it absorbs quickly."],
    [5, "The scent is subtle and lasts all day. Already on my second one."],
    [4, "Lovely texture and a little goes a long way."],
    [5, "Packaging is gorgeous and the product lives up to it."],
    [4, "Works well on my sensitive skin, no irritation at all."],
    [3, "Nice, though I'd like a larger size for the price."],
    [5, "Repurchased immediately. Truly a favourite."],
  ],
  sports: [
    [5, "Solid gear that has held up through a whole season of use."],
    [5, "Does exactly what it says and feels well built. Great price."],
    [4, "Really good quality. Took it camping and it performed well."],
    [4, "Comfortable and sturdy. Would happily buy from Stride Lab again."],
    [3, "Good, but the instructions could be clearer."],
    [5, "Lightweight, durable and easy to pack. Perfect."],
    [5, "Better than the more expensive one I had before."],
  ],
  kitchen: [
    [5, "Beautifully made and it has genuinely improved my mornings."],
    [5, "Heavy, well finished and easy to clean. Looks great on the counter."],
    [4, "Great quality. Arrived without a scratch."],
    [5, "Use it every single day. Excellent value."],
    [4, "A lovely addition to the kitchen. Would buy again."],
    [3, "Good, but it took a few tries to get the hang of it."],
    [5, "Gifted a set to my sister and she's obsessed."],
  ],
  gifts: [
    [5, "Gorgeous quality and thoughtfully packed. The perfect gift."],
    [5, "I use it every day. It feels as good as it looks."],
    [4, "Lovely detail and great value for the price."],
    [5, "Arrived quickly, wrapped beautifully. Will order again."],
    [4, "Exactly what I was after. Nice weight and finish."],
    [3, "Pretty, but smaller than I expected. Still happy."],
    [5, "Bought several as presents. Everyone has been delighted."],
  ],
};

module.exports = {
  PASSWORD,
  DOMAIN,
  CATEGORIES,
  shops,
  products,
  events,
  coupons,
  buyers,
  addresses,
  reviewText,
};
